import requests
import json
import os
import streamlit as st

from backend.database import Database

# Load Config
LINKEDIN_VERSION = "202306" # API Version

def get_active_token():
    """Retrieves the most recent valid token from the DB."""
    if 'db' in st.session_state:
        db = st.session_state.db
    else:
        db = Database()
        
    token_data = db.get_token("LinkedIn")
    if token_data:
        access_token = token_data.get('access_token')
        user_id = token_data.get('user_id')
        
        # Robust Fallback: If DB says 'Unknown', try to find ORG_ID in secrets
        if not user_id or user_id == "Unknown" or "UNKNOWN" in user_id:
             try:
                 if "connections" in st.secrets and "linkedin" in st.secrets["connections"]:
                     org_id = st.secrets["connections"]["linkedin"].get("ORG_ID")
                     if org_id and "PASTE" not in org_id:
                         user_id = f"urn:li:organization:{org_id}"
                         print(f"DEBUG: Using ORG_ID from secrets: {user_id}")
             except:
                 pass
                 
        return access_token, user_id
    return None, None

def get_user_urn(access_token):
    """
    Auto-detects your user ID using the token.
    """
    url = "https://api.linkedin.com/v2/userinfo"
    headers = {"Authorization": f"Bearer {access_token}"}
    
    resp = requests.get(url, headers=headers)
    if resp.status_code == 200:
        # Returns urn:li:person:12345
        return resp.json()['sub']
    # print(f"Error fetching URN: {resp.text}") # Quiet this, as 'unknown' is expected for w_member_social 
    return "urn:li:person:UNKNOWN" # Fallback so we can try to post anyway? No, author needs to be exact.
    # Actually, for w_member_social, we might need to rely on the "sub" from the ID token login?
    # If r_liteprofile is missing, userinfo endpoint MIGHT fail?
    # Let's hope the `get_user_urn` is not strictly needed if we saved it during login.
    return None

def post_to_linkedin(text_content, image_path=None, is_company_post=False):
    """
    Posts text (and optional image) to LinkedIn.
    """
    access_token, user_urn = get_active_token()
    if not access_token:
        return False, "No active LinkedIn connection found."

    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json",
        "X-Restli-Protocol-Version": "2.0.0",
        "LinkedIn-Version": LINKEDIN_VERSION
    }

    # 1. Determine the Author (Person or Company)
    author_urn = user_urn 
    
    if is_company_post:
        # If user explicitly requested company post (e.g. via separate setting)
        # For now, we use the primary token URN if it's already an organization
        if not author_urn.startswith("urn:li:organization:"):
             return False, "Your connected account is a personal profile, but you requested a Company Page post."
    
    if not author_urn or author_urn == "Unknown" or author_urn == "urn:li:person:UNKNOWN":
         # Last ditch effort
         author_urn = get_user_urn(access_token)
         
    if not author_urn: return False, "Could not fetch Author URN. Please re-connect."

    # 2. Upload Image (If exists)
    media_asset = None
    if image_path and os.path.exists(image_path):
        st.write("📤 Uploading image to LinkedIn...")
        media_asset = _upload_image_flow(headers, access_token, author_urn, image_path)

    # 3. Create the Post Payload
    post_data = {
        "author": author_urn,
        "lifecycleState": "PUBLISHED",
        "specificContent": {
            "com.linkedin.ugc.ShareContent": {
                "shareCommentary": {"text": text_content},
                "shareMediaCategory": "NONE" if not media_asset else "IMAGE",
            }
        },
        "visibility": {"com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"}
    }

    # Attach Image if uploaded
    if media_asset:
        post_data["specificContent"]["com.linkedin.ugc.ShareContent"]["media"] = [
            {
                "status": "READY",
                "description": {"text": "Generated by Deviceterra"},
                "media": media_asset, # The URN we got from step 2
                "title": {"text": "Visual Asset"}
            }
        ]

    # 4. Send Post
    url = "https://api.linkedin.com/v2/ugcPosts"
    response = requests.post(url, headers=headers, json=post_data)

    if response.status_code == 201:
        print("[SUCCESS] Posted successfully!")
        return True, response.json()['id']
    else:
        print(f"[ERROR] Error: {response.text}")
        return False, response.text

def _upload_image_flow(headers, access_token, author_urn, image_path):
    """
    Helper: Handles the Register -> Upload binary flow
    """
    # A. Register the Upload
    reg_url = "https://api.linkedin.com/v2/assets?action=registerUpload"
    reg_json = {
        "registerUploadRequest": {
            "recipes": ["urn:li:digitalmediaRecipe:feedshare-image"],
            "owner": author_urn,
            "serviceRelationships": [{"relationshipType": "OWNER", "identifier": "urn:li:userGeneratedContent"}]
        }
    }
    
    reg_resp = requests.post(reg_url, headers=headers, json=reg_json)
    if reg_resp.status_code != 200: return None
    
    data = reg_resp.json()
    upload_url = data['value']['uploadMechanism']['com.linkedin.digitalmedia.uploading.MediaUploadHttpRequest']['uploadUrl']
    asset_urn = data['value']['asset']

    # B. Upload the Binary File
    with open(image_path, 'rb') as f:
        # Note: LinkedIn upload URL doesn't want the standard Authorization header
        upload_headers = {"Authorization": f"Bearer {access_token}"} 
        upload_resp = requests.put(upload_url, headers=upload_headers, data=f)
        
    if upload_resp.status_code == 201:
        return asset_urn
    return None

import urllib.parse

def post_comment(parent_social_id, text_content):
    """
    Posts a comment to a LinkedIn post.
    """
    access_token, author_urn = get_active_token()
    if not access_token: return False, "No active connection."
    
    encoded_id = urllib.parse.quote(parent_social_id)
    url = f"https://api.linkedin.com/v2/socialActions/{encoded_id}/comments"
    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json",
        "X-Restli-Protocol-Version": "2.0.0",
        "LinkedIn-Version": LINKEDIN_VERSION
    }
    
    payload = {
        "actor": author_urn,
        "message": {"text": text_content}
    }
    
    try:
        r = requests.post(url, headers=headers, json=payload)
        if r.status_code == 201:
            return True, r.json().get('id')
        return False, r.text
    except Exception as e:
        return False, str(e)
